[versions]

# https://developer.android.com/jetpack/androidx/versions
activity = "1.2.3"
annotation = "1.2.0"
appcompat = "1.3.0"
arch-core = "2.1.0"
biometric = "1.0.1"
browser = "1.3.0"
camera = "1.0.0"
cardview = "1.0.0"
constraintlayout = "2.0.4"
compose = "1.0.0-rc01"
concurrent = "1.1.0"
core = "1.5.0"
dynamicanimation = "1.0.0"
exifinterface = "1.3.2"
fragment = "1.3.5"
gridlayout = "1.0.0"
interpolator = "1.0.0"
legacy-support-v4 = "1.0.0"
legacy-support-v13 = "1.0.0"
lifecycle = "2.3.1"
loader = "1.1.0"
localbroadcastmanager = "1.0.0"
media2 = "1.1.3"
navigation = "2.3.5"
paging = "2.1.2"
palette = "1.0.0"
percentlayout = "1.0.0"
preference = "1.1.1"
recyclerview = "1.2.1"
room = "2.3.0"
savedstate = "1.1.0"
security-crypto = "1.0.0"
startup = "1.0.0"
swiperefreshlayout = "1.1.0"
work = "2.5.0"
test-Core = "1.4.0"
test-espresso = "3.4.0"
test-ext = "1.1.3"
test-uiautomator = "2.2.0"
tracing = "1.0.0"
transition = "1.4.1"
vectordrawable = "1.1.0"
versionedparcelable = "1.1.1"
viewpager2 = "1.0.0"
webkit = "1.4.0"


[libraries]

activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }

arch-core-common = { module = "androidx.arch.core:core-common", version.ref = "arch-core" }
arch-core-runtime = { module = "androidx.arch.core:core-runtime", version.ref = "arch-core" }
arch-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "arch-core" }

biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }

browser = { module = "androidx.browser:browser", version.ref = "browser" }

camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera" }
camera-core = { module = "androidx.camera:camera-core", version.ref = "camera" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera" }

cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }

compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
compose-runtime-rxjava2 = { module = "androidx.compose.runtime:runtime-rxjava2", version.ref = "compose" }
compose-runtime-rxjava3 = { module = "androidx.compose.runtime:runtime-rxjava3", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }

concurrent-futures-ktx = { module = "androidx.concurrent:concurrent-futures-ktx", version.ref = "concurrent" }

constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }

core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }

dynamicanimation = { module = "androidx.dynamicanimation:dynamicanimation", version.ref = "dynamicanimation" }

exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }

fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "fragment" }

gridlayout = { module = "androidx.gridlayout:gridlayout", version.ref = "gridlayout" }

interpolator = { module = "androidx.interpolator:interpolator", version.ref = "interpolator" }

legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacy-support-v4" }
legacy-support-v13 = { module = "androidx.legacy:legacy-support-v13", version.ref = "legacy-support-v13" }

lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
lifecycle-livedata-core-ktx = { module = "androidx.lifecycle:lifecycle-livedata-core-ktx", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
lifecycle-reactivestreams-ktx = { module = "androidx.lifecycle:lifecycle-reactivestreams-ktx", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }

loader = { module = "androidx.loader:loader", version.ref = "loader" }

localbroadcastmanager =  { module = "androidx.localbroadcastmanager:localbroadcastmanager", version.ref = "localbroadcastmanager" }

media2-player = { module = "androidx.media2:media2-player", version.ref = "media2" }
media2-session = { module = "androidx.media2:media2-session", version.ref = "media2" }
media2-widget = { module = "androidx.media2:media2-widget", version.ref = "media2" }

navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "navigation" }

paging-common = { module = "androidx.paging:paging-common", version.ref = "paging" }
paging-guava = { module = "androidx.paging:paging-guava", version.ref = "paging" }
paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }
paging-rxjava2 = { module = "androidx.paging:paging-rxjava2", version.ref = "paging" }
paging-rxjava3 = { module = "androidx.paging:paging-rxjava3", version.ref = "paging" }

palette = { module = "androidx.palette:palette", version.ref = "palette" }

percentlayout = { module = "androidx.percentlayout:percentlayout", version.ref = "percentlayout" }

preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference" }

recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }

room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-rxjava2 = { module = "androidx.room:room-rxjava2", version.ref = "room" }
room-rxjava3 = { module = "androidx.room:room-rxjava3", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

savedstate-ktx = { module = "androidx.savedstate:savedstate-ktx", version.ref = "savedstate" }

security-crypto = { module = "androidx.security:security-crypto", version.ref = "security-crypto" }

startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startup" }

swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }

test-ktx = { module = "androidx.test:core-ktx", version.ref = "test-Core" }
test-monitor = { module = "androidx.test:monitor", version.ref = "test-Core" }
test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "test-Core" }
test-rules = { module = "androidx.test:rules", version.ref = "test-Core" }
test-runner = { module = "androidx.test:runner", version.ref = "test-Core" }

test-espresso-Core = { module = "androidx.test.espresso:espresso-core", version.ref = "test-espresso" }
test-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "test-espresso" }
test-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "test-espresso" }
test-espresso-web = { module = "androidx.test.espresso:espresso-web", version.ref = "test-espresso" }

test-ext-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "test-ext" }
test-ext-truth = { module = "androidx.test.ext:truth", version.ref = "test-ext" }

test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "test-uiautomator" }

tracing-ktx = { module = "androidx.tracing:tracing-ktx", version.ref = "tracing" }

transition-ktx = { module = "androidx.transition:transition-ktx", version.ref = "transition" }

vectordrawable-Core = { module = "androidx.vectordrawable:vectordrawable", version.ref = "vectordrawable" }
vectordrawable-animated = { module = "androidx.vectordrawable:vectordrawable-animated", version.ref = "vectordrawable" }
vectordrawable-seekable = { module = "androidx.vectordrawable:vectordrawable-seekable", version.ref = "vectordrawable" }

versionedparcelable = { module = "androidx.versionedparcelable:versionedparcelable", version.ref = "versionedparcelable" }

viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2"}

webkit = { module = "androidx.webkit:webkit", version.ref = "webkit"}

work-gcm = { module = "androidx.work:work-gcm", version.ref = "work"}
work-multiprocess = { module = "androidx.work:work-multiprocess", version.ref = "work"}
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work"}
work-rxjava2 = { module = "androidx.work:work-rxjava2", version.ref = "work"}
work-rxjava3 = { module = "androidx.work:work-rxjava3", version.ref = "work"}
work-testing = { module = "androidx.work:work-testing", version.ref = "work"}

