[versions]

# https://developer.android.com/studio/releases/gradle-plugin
android-gradle = "7.1.0-rc01"

# https://github.com/google/bundletool/releases
bundletool = "1.8.0"

# https://github.com/google/desugar_jdk_libs
desugar = "1.1.5"

# https://kotlinlang.org/docs/releases.html#release-details
kotlin = "1.6.10"

# https://github.com/Kotlin/kotlinx.coroutines/releases
kotlinx-coroutines = "1.6.0"

# https://github.com/google/ksp/releases
ksp = "1.6.10-1.0.1"

# https://github.com/pinterest/ktlint/releases
ktlint = "0.43.2"

commons-codec = "1.15"

# https://junit.org/junit4/
junit4 = "4.13.2"

# https://github.com/mockito/mockito/releases
mockito-Core = '4.2.0'

# https://github.com/mockito/mockito-kotlin/releases
mockito-kotlin = '4.0.0'

# https://github.com/robolectric/robolectric/releases/
robolectric = "4.7.3"

[libraries]

android-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradle" }

junit4 = { module = "junit:junit", version.ref = "junit4" }

kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ktlint = { module = "com.pinterest:ktlint", version.ref = "ktlint" }

kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-test-junit =  { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin"}

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-rx2 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx2", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-rx3 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx3", version.ref = "kotlinx-coroutines" }

mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito-Core" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito-Core" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }

robolectric-Core = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
robolectric-shadows-httpclient = { module = "org.robolectric:shadows-httpclient", version.ref = "robolectric" }
robolectric-shadows-playservices = { module = "org.robolectric:shadows-playservices", version.ref = "robolectric" }

commons-codec = { module = "commons-codec:commons-codec", version.ref = "commons-codec" }
